// ===== DECKS DE EXEMPLO PRÉ-PRONTOS =====
// CARDS NA ORDEM: PORTUGUÊS → IDIOMA ESTRANGEIRO

export const EXAMPLE_DECKS = {
  ingles: {
    name: "Inglês - 30 Palavras Essenciais",
    description: "Vocabulário fundamental para iniciantes",
    language: "Inglês 🇺🇸",
    cards: [
      { front: "Olá", back: "Hello" },
      { front: "Adeus", back: "Goodbye" },
      { front: "Por favor", back: "Please" },
      { front: "Obrigado(a)", back: "Thank you" },
      { front: "Sim", back: "Yes" },
      { front: "Não", back: "No" },
      { front: "Água", back: "Water" },
      { front: "Comida", back: "Food" },
      { front: "Ajuda", back: "Help" },
      { front: "Hoje", back: "Today" },
      { front: "Amanhã", back: "Tomorrow" },
      { front: "Ontem", back: "Yesterday" },
      { front: "Bom dia", back: "Good morning" },
      { front: "Boa noite", back: "Good night" },
      { front: "Como você está?", back: "How are you?" },
      { front: "Estou bem", back: "I'm fine" },
      { front: "Meu nome é", back: "My name is" },
      { front: "Onde", back: "Where" },
      { front: "Quando", back: "When" },
      { front: "Por quê", back: "Why" },
      { front: "Como", back: "How" },
      { front: "O quê", back: "What" },
      { front: "Quem", back: "Who" },
      { front: "Amigo(a)", back: "Friend" },
      { front: "Família", back: "Family" },
      { front: "Casa", back: "House" },
      { front: "Tempo/Hora", back: "Time" },
      { front: "Dinheiro", back: "Money" },
      { front: "Eu te amo", back: "I love you" },
      { front: "Com licença", back: "Excuse me" }
    ]
  },

  espanhol: {
    name: "Espanhol - 30 Palavras Essenciais",
    description: "Vocabulário fundamental para iniciantes",
    language: "Espanhol 🇪🇸",
    cards: [
      { front: "Olá", back: "Hola" },
      { front: "Adeus", back: "Adiós" },
      { front: "Por favor", back: "Por favor" },
      { front: "Obrigado(a)", back: "Gracias" },
      { front: "Sim", back: "Sí" },
      { front: "Não", back: "No" },
      { front: "Água", back: "Agua" },
      { front: "Comida", back: "Comida" },
      { front: "Ajuda", back: "Ayuda" },
      { front: "Hoje", back: "Hoy" },
      { front: "Amanhã", back: "Mañana" },
      { front: "Ontem", back: "Ayer" },
      { front: "Bom dia", back: "Buenos días" },
      { front: "Boa noite", back: "Buenas noches" },
      { front: "Como você está?", back: "¿Cómo estás?" },
      { front: "Estou bem", back: "Estoy bien" },
      { front: "Meu nome é", back: "Me llamo" },
      { front: "Onde", back: "Dónde" },
      { front: "Quando", back: "Cuándo" },
      { front: "Por quê", back: "Por qué" },
      { front: "Como", back: "Cómo" },
      { front: "O quê", back: "Qué" },
      { front: "Quem", back: "Quién" },
      { front: "Amigo", back: "Amigo" },
      { front: "Família", back: "Familia" },
      { front: "Casa", back: "Casa" },
      { front: "Tempo", back: "Tiempo" },
      { front: "Dinheiro", back: "Dinero" },
      { front: "Eu te amo", back: "Te quiero" },
      { front: "Desculpe", back: "Perdón" }
    ]
  },

  frances: {
    name: "Francês - 30 Palavras Essenciais",
    description: "Vocabulário fundamental para iniciantes",
    language: "Francês 🇫🇷",
    cards: [
      { front: "Olá/Bom dia", back: "Bonjour" },
      { front: "Adeus", back: "Au revoir" },
      { front: "Por favor", back: "S'il vous plaît" },
      { front: "Obrigado(a)", back: "Merci" },
      { front: "Sim", back: "Oui" },
      { front: "Não", back: "Non" },
      { front: "Água", back: "Eau" },
      { front: "Comida", back: "Nourriture" },
      { front: "Ajuda", back: "Aide" },
      { front: "Hoje", back: "Aujourd'hui" },
      { front: "Amanhã", back: "Demain" },
      { front: "Ontem", back: "Hier" },
      { front: "Boa noite", back: "Bonsoir" },
      { front: "Como você está?", back: "Comment allez-vous?" },
      { front: "Estou bem", back: "Je vais bien" },
      { front: "Meu nome é", back: "Je m'appelle" },
      { front: "Onde", back: "Où" },
      { front: "Quando", back: "Quand" },
      { front: "Por quê", back: "Pourquoi" },
      { front: "Como", back: "Comment" },
      { front: "O quê", back: "Quoi" },
      { front: "Quem", back: "Qui" },
      { front: "Amigo", back: "Ami" },
      { front: "Família", back: "Famille" },
      { front: "Casa", back: "Maison" },
      { front: "Tempo", back: "Temps" },
      { front: "Dinheiro", back: "Argent" },
      { front: "Eu te amo", back: "Je t'aime" },
      { front: "Desculpe", back: "Pardon" },
      { front: "Com licença", back: "Excusez-moi" }
    ]
  },

  italiano: {
    name: "Italiano - 30 Palavras Essenciais",
    description: "Vocabulário fundamental para iniciantes",
    language: "Italiano 🇮🇹",
    cards: [
      { front: "Olá/Tchau", back: "Ciao" },
      { front: "Adeus", back: "Arrivederci" },
      { front: "Por favor", back: "Per favore" },
      { front: "Obrigado(a)", back: "Grazie" },
      { front: "Sim", back: "Sì" },
      { front: "Não", back: "No" },
      { front: "Água", back: "Acqua" },
      { front: "Comida", back: "Cibo" },
      { front: "Ajuda", back: "Aiuto" },
      { front: "Hoje", back: "Oggi" },
      { front: "Amanhã", back: "Domani" },
      { front: "Ontem", back: "Ieri" },
      { front: "Bom dia", back: "Buongiorno" },
      { front: "Boa noite", back: "Buonasera" },
      { front: "Como você está?", back: "Come stai?" },
      { front: "Estou bem", back: "Sto bene" },
      { front: "Meu nome é", back: "Mi chiamo" },
      { front: "Onde", back: "Dove" },
      { front: "Quando", back: "Quando" },
      { front: "Por quê", back: "Perché" },
      { front: "Como", back: "Come" },
      { front: "O quê", back: "Cosa" },
      { front: "Quem", back: "Chi" },
      { front: "Amigo", back: "Amico" },
      { front: "Família", back: "Famiglia" },
      { front: "Casa", back: "Casa" },
      { front: "Tempo", back: "Tempo" },
      { front: "Dinheiro", back: "Soldi" },
      { front: "Eu te amo", back: "Ti amo" },
      { front: "Desculpe", back: "Scusa" }
    ]
  },

  japones: {
    name: "Japonês - 30 Palavras Essenciais",
    description: "Vocabulário fundamental para iniciantes",
    language: "Japonês 🇯🇵",
    cards: [
      { front: "Olá", back: "こんにちは (Konnichiwa)" },
      { front: "Adeus", back: "さようなら (Sayonara)" },
      { front: "Por favor", back: "お願いします (Onegaishimasu)" },
      { front: "Obrigado(a)", back: "ありがとう (Arigatou)" },
      { front: "Sim", back: "はい (Hai)" },
      { front: "Não", back: "いいえ (Iie)" },
      { front: "Água", back: "水 (Mizu)" },
      { front: "Comida", back: "食べ物 (Tabemono)" },
      { front: "Ajuda", back: "助けて (Tasukete)" },
      { front: "Hoje", back: "今日 (Kyou)" },
      { front: "Amanhã", back: "明日 (Ashita)" },
      { front: "Ontem", back: "昨日 (Kinou)" },
      { front: "Bom dia", back: "おはよう (Ohayou)" },
      { front: "Boa noite", back: "こんばんは (Konbanwa)" },
      { front: "Como você está?", back: "元気ですか (Genki desuka)" },
      { front: "Estou bem", back: "元気です (Genki desu)" },
      { front: "Eu sou/Meu nome é", back: "私は (Watashi wa)" },
      { front: "Onde", back: "どこ (Doko)" },
      { front: "Quando", back: "いつ (Itsu)" },
      { front: "Por quê", back: "なぜ (Naze)" },
      { front: "Como", back: "どう (Dou)" },
      { front: "O quê", back: "何 (Nani)" },
      { front: "Quem", back: "誰 (Dare)" },
      { front: "Amigo", back: "友達 (Tomodachi)" },
      { front: "Família", back: "家族 (Kazoku)" },
      { front: "Casa", back: "家 (Ie)" },
      { front: "Tempo/Hora", back: "時間 (Jikan)" },
      { front: "Dinheiro", back: "お金 (Okane)" },
      { front: "Eu te amo", back: "愛してる (Aishiteru)" },
      { front: "Desculpe/Com licença", back: "すみません (Sumimasen)" }
    ]
  },

  coreano: {
    name: "Coreano - 30 Palavras Essenciais",
    description: "Vocabulário fundamental para iniciantes",
    language: "Coreano 🇰🇷",
    cards: [
      { front: "Olá", back: "안녕하세요 (Annyeonghaseyo)" },
      { front: "Adeus", back: "안녕히 가세요 (Annyeonghi gaseyo)" },
      { front: "Por favor", back: "제발 (Jebal)" },
      { front: "Obrigado(a)", back: "감사합니다 (Gamsahamnida)" },
      { front: "Sim", back: "네 (Ne)" },
      { front: "Não", back: "아니요 (Aniyo)" },
      { front: "Água", back: "물 (Mul)" },
      { front: "Comida", back: "음식 (Eumsik)" },
      { front: "Ajuda", back: "도와주세요 (Dowajuseyo)" },
      { front: "Hoje", back: "오늘 (Oneul)" },
      { front: "Amanhã", back: "내일 (Naeil)" },
      { front: "Ontem", back: "어제 (Eoje)" },
      { front: "Bom dia", back: "좋은 아침 (Joeun achim)" },
      { front: "Boa noite", back: "안녕히 주무세요 (Annyeonghi jumuseyo)" },
      { front: "Como você está?", back: "어떻게 지내세요? (Eotteoke jinaeseyo)" },
      { front: "Estou bem", back: "잘 지내요 (Jal jinaeyo)" },
      { front: "Meu nome é", back: "제 이름은 (Je ireumeun)" },
      { front: "Onde", back: "어디 (Eodi)" },
      { front: "Quando", back: "언제 (Eonje)" },
      { front: "Por quê", back: "왜 (Wae)" },
      { front: "Como", back: "어떻게 (Eotteoke)" },
      { front: "O quê", back: "뭐 (Mwo)" },
      { front: "Quem", back: "누구 (Nugu)" },
      { front: "Amigo", back: "친구 (Chingu)" },
      { front: "Família", back: "가족 (Gajok)" },
      { front: "Casa", back: "집 (Jip)" },
      { front: "Tempo/Hora", back: "시간 (Sigan)" },
      { front: "Dinheiro", back: "돈 (Don)" },
      { front: "Eu te amo", back: "사랑해 (Saranghae)" },
      { front: "Desculpe", back: "미안해요 (Mianhaeyo)" }
    ]
  },

  chines: {
    name: "Chinês - 30 Palavras Essenciais",
    description: "Vocabulário fundamental para iniciantes (Mandarim)",
    language: "Chinês 🇨🇳",
    cards: [
      { front: "Olá", back: "你好 (Nǐ hǎo)" },
      { front: "Adeus", back: "再见 (Zàijiàn)" },
      { front: "Por favor", back: "请 (Qǐng)" },
      { front: "Obrigado(a)", back: "谢谢 (Xièxiè)" },
      { front: "Sim", back: "是 (Shì)" },
      { front: "Não", back: "不是 (Bù shì)" },
      { front: "Água", back: "水 (Shuǐ)" },
      { front: "Comida", back: "食物 (Shíwù)" },
      { front: "Ajuda", back: "帮助 (Bāngzhù)" },
      { front: "Hoje", back: "今天 (Jīntiān)" },
      { front: "Amanhã", back: "明天 (Míngtiān)" },
      { front: "Ontem", back: "昨天 (Zuótiān)" },
      { front: "Bom dia", back: "早上好 (Zǎoshang hǎo)" },
      { front: "Boa noite", back: "晚安 (Wǎn'ān)" },
      { front: "Como você está?", back: "你好吗? (Nǐ hǎo ma)" },
      { front: "Estou bem", back: "我很好 (Wǒ hěn hǎo)" },
      { front: "Meu nome é", back: "我叫 (Wǒ jiào)" },
      { front: "Onde", back: "哪里 (Nǎlǐ)" },
      { front: "Quando", back: "什么时候 (Shénme shíhòu)" },
      { front: "Por quê", back: "为什么 (Wèishéme)" },
      { front: "Como", back: "怎么 (Zěnme)" },
      { front: "O quê", back: "什么 (Shénme)" },
      { front: "Quem", back: "谁 (Shéi)" },
      { front: "Amigo", back: "朋友 (Péngyǒu)" },
      { front: "Família", back: "家人 (Jiārén)" },
      { front: "Casa", back: "家 (Jiā)" },
      { front: "Tempo/Hora", back: "时间 (Shíjiān)" },
      { front: "Dinheiro", back: "钱 (Qián)" },
      { front: "Eu te amo", back: "我爱你 (Wǒ ài nǐ)" },
      { front: "Desculpe", back: "对不起 (Duìbùqǐ)" }
    ]
  }
};